version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-local
        ports:
        - '5000:5000'
        volumes:
        - '.:/usr/src/app'
        container_name: portfolio
        command: npm start

